### ISSUE TITLE
Error code 6 - EOF Could not match command prompt

### ISSUE THREAD

**Issue by shagy234** [udhos/jazigo#7]
I keep getting this error from some of my mikrotik devices, others are working ok.

2023/05/19 10:30:26 errlog: push: /home/ramiro/jazigo/log/BOL_1381_DDO.errlog: 2023-05-19 10:30:26.558389729 -0300 -03 m=+1820.852824878 success=false elapsed=20.826305183s model=mikrotik dev=BOL_1381_DDO host=192.168.72.213:22 transport=ssh code=6 message=[commands: sendCommands: EOF could not match command prompt: EOF buf=[</system resource print]]
2023/05/19 10:30:26 Scan: recv mikrotik BOL_1381_DDO 192.168.72.213:22 ssh msg=[commands: sendCommands: EOF could not match command prompt: EOF buf=[</system resource print]] code=6 wait=3 remain=0 skipped=4 elap=20.82879876s

On the mikrotik I see that jazigo logs in and out properly. Sometimes i see "auth timeout" events on the log tho..

**Comment by udhos** [comment]
For some reason it could not match the Mikrotik command prompt after sending some command.
It received a connection closed instead (EOF).

Can you manually enter the backup commands into Mikrotik and see why it does not match that prompt pattern?
Try to check if any backup command is answered with a connection closed instead of a command prompt.

You can try to change the prompt pattern in the Device Properties tab:
```
attr:
    disabledpromptpattern: \[[^\[\]]+\]\s*>\s*$
    enabledpromptpattern: \[[^\[\]]+\]\s*>\s*$
```

You could also attempt to change the backup commands for the Mikrotik in the Device Properties tab:
```
attr:
    commandlist:
    - /system resource print
    - /export
    - /export verbose
```

**Comment by shagy234** [comment]
I have changed the commands but it still happens, the "solution" was to use telnet instead of ssh on those devices.

Thanks!
